# Generated by Django 5.0.6 on 2024-07-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_alter_product_short_description_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_product',
            field=models.ImageField(upload_to='product', verbose_name='عکس محصول'),
        ),
    ]
