# Generated by Django 5.0.6 on 2024-07-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_alter_product_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_product',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='عکس محصول'),
        ),
    ]
