# Generated by Django 5.0.6 on 2024-07-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='موضوع پیام')),
                ('email', models.EmailField(max_length=300, verbose_name='پست الکترونیک')),
                ('full_name', models.CharField(max_length=300, verbose_name='نام ونام خانوادگی')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_read_by_admin', models.BooleanField(verbose_name='خوانده شده توسط ادمین')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('response', models.TextField(blank=True, null=True, verbose_name='پاسخ تماس با ما')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'لیست تماس با ما',
            },
        ),
    ]
