# Generated by Django 5.0.6 on 2024-07-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0005_article_created_at_article_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='selected_categories',
            field=models.ManyToManyField(related_name='articles', to='article_module.articlecategory', verbose_name='دسته بندی ها'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.CharField(max_length=50, verbose_name='توضیحات کوتاه'),
        ),
    ]
